// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB80dCFxLSAwmYF9pqGi_LdryIDRk75g2w',
    appId: '1:859312623693:web:c1a9f4fb6d277ca6954c04',
    messagingSenderId: '859312623693',
    projectId: 'campusconnect-36492',
    authDomain: 'campusconnect-36492.firebaseapp.com',
    storageBucket: 'campusconnect-36492.appspot.com',
    measurementId: 'G-JH1B7THPMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQg0Vlx0LFKE_XhNKYNB5PV9fX1RFqwiA',
    appId: '1:859312623693:android:e4931b0d0bcfca3a954c04',
    messagingSenderId: '859312623693',
    projectId: 'campusconnect-36492',
    storageBucket: 'campusconnect-36492.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQbXN7TnNLIZ-0VpXBkueuQ_C2fQQqKS0',
    appId: '1:859312623693:ios:edc747aef0f2c7d5954c04',
    messagingSenderId: '859312623693',
    projectId: 'campusconnect-36492',
    storageBucket: 'campusconnect-36492.appspot.com',
    iosBundleId: 'com.example.firebaseServicesWithBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQbXN7TnNLIZ-0VpXBkueuQ_C2fQQqKS0',
    appId: '1:859312623693:ios:4cd0ba7454fdcda2954c04',
    messagingSenderId: '859312623693',
    projectId: 'campusconnect-36492',
    storageBucket: 'campusconnect-36492.appspot.com',
    iosBundleId: 'com.example.firebaseServicesWithBloc.RunnerTests',
  );
}
